version: "3"
services:
    ros2:
        image: adohaha/fun_ros:foxy
        volumes:
            - ./jupyter_notebooks:/home/ubuntu/turtlebot3_ws/src/jupyter_notebooks
            - ./world:/opt/ros/foxy/share/turtlebot3_gazebo/models/turtlebot3_world
        ports: 
            - 6080:80
            - 8888:8888
        shm_size: '2gb'
        container_name: ros_fun
        command: "bash -i /home/ubuntu/run_jupyter.sh"
    
      
